---
title: "figures"
author: "JT_Miller"
date: "4/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Figures created from the data.

```{r}
ggplot(data = penguins_clean,  aes (x = species, y = flipper_length)) +
  geom_boxplot()
```

```{r}
penguins_flip_gender <- ggplot(data = penguins_gender_clean, aes (x = species, y = flipper_length, color = sex)) +
  geom_boxplot() +
  labs( x = "Penguin Species", y = "Flipper Length (mm)", title = "Flipper Length of Penguins") +
  theme_bw()

penguins_flip_gender + theme(axis.text = element_text(size = 7))
```

```{r}
ggplot(data = penguins_gender_clean, aes ( x= flipper_length, )) +
  geom_histogram() +
  labs(y = "Frequency", x = "Flipper Length", title = "Flipper Length of Penguins") +
  theme_bw()


```

```{r}
ggplot(data = penguins_gender_clean, aes ( x= flipper_length, color = sex)) +
  geom_histogram() +
  facet_wrap(~sex) +
  labs(y = "Frequency", x = "Flipper Length", title = "Flipper Length of Penguins") +
  theme_bw()
```

```{r}
ggplot(data = penguins_gender_clean, aes ( x= flipper_length, )) +
  geom_histogram() +
  facet_wrap(~species) +
  labs(y = "Frequency", x = "Flipper Length", title = "Flipper Length of Penguins") +
  theme_bw()
```

```{r}
ggplot(data = penguins_clean_m, aes ( x= body_mass, )) +
  geom_histogram() +
  labs(y = "Frequency", x = "Body Mass", title = "Body Mass of Penguins") +
  theme_bw()
```


```{r}
ggplot(data = penguins_clean_m, aes ( x= body_mass_log, )) +
  geom_histogram() +
  labs(y = "Frequency", x = "Log of Body Mass", title = "Body Mass of Penguins") +
  theme_bw()

```


```{r}
ggplot(data = penguins_clean_m,  aes (x = clutch_completion, y = body_mass)) +
  geom_boxplot() + 
  labs(title = "Body mass for success of raising clutch")

``` 
